### ISSUE TITLE
Improve the template loader performance

### ISSUE THREAD

**Issue by juchi** [open-orchestra/open-orchestra-cms-bundle#1856]
## Informations
**Orchestra Version** : 1.0, 1.1

**Issue Type**: 
- [x] Bug
- [ ] Feature request
- [ ] Question

### Actual behavior
When loading an underscore template that is not in local storage, there is no verification if this template is currently already being requested by the template loader. Consequently, using the same template several times on a page leads to several ajax requests for the same resource. This can slow down the display noticeably, for instance in the media library when there are lots of images.
### Expected behavior
Only 1 http request should be sent for a given template, other components requesting the data should be placed on hold, waiting for the first ajax request to succeed in order to read the template from local storage directly.
### Steps to reproduce the problem
* Clear local storage
* Go on a list page with several lines
* See the "actions" template being loaded several times

**Comment by alavieille** [comment]
It is fixed in this PR https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1880
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1879
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/288
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/287
for the version 1.1 and 1.2
thanks

**Comment by juchi** [comment]
Hi,
I'm not sure this solves the actual issue reported. From the identified PRs, I understand that there is now a template-preloading process created in order to avoid subsequent multiple template calls. This fixes the issue in some specific cases, however the template loader itself is still not working as expected in other cases.
The template loader can be used in custom projects and the problem stills arises here and it feels clumsy to have to preload each possible template before. In some cases it's not even possible to do so. Hence the "expected behavior" explanation of how i should behave (in my opinion).

Could you bring some clarification over my point ?
Thanks

**Comment by itkg-nanne** [comment]
The Pr fixe all OO backoffice multiple template calls. This method could be used in custom context as this template-preloading could be done in app entry point. Furthermore, in custom context, a dedicated loader could be developped with a call stack containing unique entries. Whatever, the next version of OO won't use templates and local storage in the same way.

**Comment by juchi** [comment]
ping @pdenis for follow up
